### ISSUE TITLE
BiteOpt in Python

### ISSUE THREAD

**Issue by infinity77** [avaneev/biteopt#1] opened 2020-07-15 14:30 UTC
Hi Aleksey,

I'm not sure if you remember, but we had an exchange of emails a couple of years ago exploring the possibility to have BiteOpt in Python. Well, I have converted it today just for fun - I could have used wrappers like PyBind11 or Boost but I know almost nothing about C++ and I decided to convert the code to Python directly.

It appears that it's almost working, but funnily enough the biggest problems I am having are related to the biternd.h module, as I don't understand what you're doing there. If I can't replicate the exact random numbers as you have n your C++ code then I can't check the rest of the code for correctness.

I have added a few `printf` statements in the CBiteRnd class jut to understand what's going on, like this:

```cpp
class CBiteRnd
{
public:
    /**
     * Function initializes *this PRNG object.
     *
     * @param NewSeed New random seed value.
     */

    void init( const int NewSeed )
    {
        seed = NewSeed;
        printf("RndValue1 = %d\n", ( seed ));

        // Skip first values to make PRNG "settle down".

        seed = 500009 * seed + 300119;
        printf("RndValue2 = %d\n", ( seed ));
        seed = 500009 * seed + 300119;
        printf("RndValue3 = %d\n", ( seed ));
    }

    /**
     * @return Random number in the range [0; 1).
     */

    double getRndValue()
    {
        printf("RndValue4 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("RndValue5 = %d\n", seed);

        return((( seed >> 32 ) & 0x3FFFFFFF ) * 9.31322574615478516e-10 );
    }

    /**
     * @return Scale of "raw" random values returned by functions with the
     * "raw" suffix.
     */

    static int32_t getRawScale()
    {
        return( 0x40000000 );
    }

    /**
     * @return Uniformly-distributed random number in the range [0; 1), in the
     * "raw" scale.
     */

    int32_t getUniformRaw()
    {
        printf("UniformRAW1 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("UniformRAW1 = %d\n", seed);

        return( (int32_t) (( seed >> 32 ) & 0x3FFFFFFF ));
    }

    /**
     * @return TPDF random number in the range (-1; 1), in the "raw" scale.
     */

    int32_t getTPDFRaw()
    {
        printf("RndValueRAW1 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("RndValueRAW2 = %d\n", seed);
        const int32_t v1 = (int32_t) (( seed >> 32 ) & 0x3FFFFFFF );
        seed = 500009 * seed + 300119;
        printf("RndValueRAW3 = %d\n", seed);
        const int32_t v2 = (int32_t) (( seed >> 32 ) & 0x3FFFFFFF );

        return( v1 - v2 );
    }

private:
    uint64_t seed; ///< The current random seed value.
        ///<
};

```

Now, by making it print the few iterations on screen, I get the following output:

```
RndValue1 = 1
RndValue2 = 800128
RndValue3 = 639542743
RndValue4 = 639542743
RndValue5 = -367371578
RndValue4 = -367371578
RndValue5 = -1933728755
RndValue4 = -1933728755
RndValue5 = 1256916844
RndValue4 = 1256916844
RndValue5 = 55029923
RndValue4 = 55029923
RndValue5 = 1896571250
RndValue4 = 1896571250
RndValue5 = -314711655
RndValue4 = -314711655
RndValue5 = 352186072
RndValue4 = 352186072
RndValue5 = -1748128529
RndValue4 = -1748128529
RndValue5 = 1681954206
RndValue4 = 1681954206
```

And there are a couple of things that I do not understand:

1. `seed` is defined as uint64_t - how can it possibly become negative (as it does in line 5 on my output `RndValue5 = --367371578`)??
2. At least in Python, applying the bitshift operator ``>>`` to a negative integer does not give what I can see from C++;
```
[In211]: s2 = -367371578
[In211]: s2 >> 32
Out[211]: -1
```

Maybe you can shed some light and make me understand what I am doing wrong here?

Thank you.

Andrea.

**Comment by avaneev** [comment] 2020-07-15 23:56
Re: [avaneev/biteopt] BiteOpt in Python (#1)



Greetings,

biternd is a simple LCG random number generator, can be replaced with any random number generator. LCG random is sufficient for my optimization algorithms.

Best regards,
Aleksey Vaneev
https://www.voxengo.com/

---

Wednesday, July 15, 2020, 5:30:24 PM, you wrote:





Hi Aleksey,
I'm not sure if you remember, but we had an exchange of emails a couple of years ago exploring the possibility to have BiteOpt in Python. Well, I have converted it today just for fun - I could have used wrappers like PyBind11 or Boost but I know almost nothing about C++ and I decided to convert the code to Python directly.
It appears that it's almost working, but funnily enough the biggest problems I am having are related to the biternd.h module, as I don't understand what you're doing there. If I can't replicate the exact random numbers as you have n your C++ code then I can't check the rest of the code for correctness.
I have added a few printf statements in the CBiteRnd class jut to understand what's going on, like this:
class CBiteRnd
{
public:
    /**
     * Function initializes *this PRNG object.
     *
     * @param NewSeed New random seed value.
     */

    void init( const int NewSeed )
    {
        seed = NewSeed;
        printf("RndValue1 = %d\n", ( seed ));

        // Skip first values to make PRNG "settle down".

        seed = 500009 * seed + 300119;
        printf("RndValue2 = %d\n", ( seed ));
        seed = 500009 * seed + 300119;
        printf("RndValue3 = %d\n", ( seed ));
    }

    /**
     * @return Random number in the range [0; 1).
     */

    double getRndValue()
    {
        printf("RndValue4 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("RndValue5 = %d\n", seed);

        return((( seed >> 32 ) & 0x3FFFFFFF ) * 9.31322574615478516e-10 );
    }

    /**
     * @return Scale of "raw" random values returned by functions with the
     * "raw" suffix.
     */

    static int32_t getRawScale()
    {
        return( 0x40000000 );
    }

    /**
     * @return Uniformly-distributed random number in the range [0; 1), in the
     * "raw" scale.
     */

    int32_t getUniformRaw()
    {
        printf("UniformRAW1 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("UniformRAW1 = %d\n", seed);

        return( (int32_t) (( seed >> 32 ) & 0x3FFFFFFF ));
    }

    /**
     * @return TPDF random number in the range (-1; 1), in the "raw" scale.
     */

    int32_t getTPDFRaw()
    {
        printf("RndValueRAW1 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("RndValueRAW2 = %d\n", seed);
        const int32_t v1 = (int32_t) (( seed >> 32 ) & 0x3FFFFFFF );
        seed = 500009 * seed + 300119;
        printf("RndValueRAW3 = %d\n", seed);
        const int32_t v2 = (int32_t) (( seed >> 32 ) & 0x3FFFFFFF );

        return( v1 - v2 );
    }

private:
    uint64_t seed; ///< The current random seed value.
        ///<
};
Now, by making it print the few iterations on screen, I get the following output:
RndValue1 = 1
?RndValue2 = 800128
?RndValue3 = 639542743
?RndValue4 = 639542743
?RndValue5 = -367371578
?RndValue4 = -367371578
?RndValue5 = -1933728755
?RndValue4 = -1933728755
?RndValue5 = 1256916844
?RndValue4 = 1256916844
?RndValue5 = 55029923
?RndValue4 = 55029923
?RndValue5 = 1896571250
?RndValue4 = 1896571250
?RndValue5 = -314711655
?RndValue4 = -314711655
?RndValue5 = 352186072
?RndValue4 = 352186072
?RndValue5 = -1748128529
?RndValue4 = -1748128529
?RndValue5 = 1681954206
?RndValue4 = 1681954206
?
And there are a couple of things that I do not understand:


seed is defined as uint64_t - how can it possibly become negative (as it does in line 5 on my output RndValue5 = --367371578)??
At least in Python, applying the bitshift operator >> to a negative integer does not give what I can see from C++;

[In211]: s2 = -367371578
?[In211]: s2 >> 32
?Out[211]: -1
?
Maybe you can shed some light and make me understand what I am doing wrong here?
Thank you.
Andrea.

**Comment by avaneev** [comment] 2020-07-15 23:56
Please use printf ("%llu") for 64-bit unsigned numbers.

**Comment by avaneev** [comment] 2020-07-15 23:57
Re: [avaneev/biteopt] BiteOpt in Python (#1)



Greetings,

Please use printf ("%llu") for 64-bit unsigned numbers.

Best regards,
Aleksey Vaneev
https://www.voxengo.com/

---

Wednesday, July 15, 2020, 5:30:24 PM, you wrote:





Hi Aleksey,
I'm not sure if you remember, but we had an exchange of emails a couple of years ago exploring the possibility to have BiteOpt in Python. Well, I have converted it today just for fun - I could have used wrappers like PyBind11 or Boost but I know almost nothing about C++ and I decided to convert the code to Python directly.
It appears that it's almost working, but funnily enough the biggest problems I am having are related to the biternd.h module, as I don't understand what you're doing there. If I can't replicate the exact random numbers as you have n your C++ code then I can't check the rest of the code for correctness.
I have added a few printf statements in the CBiteRnd class jut to understand what's going on, like this:
class CBiteRnd
{
public:
    /**
     * Function initializes *this PRNG object.
     *
     * @param NewSeed New random seed value.
     */

    void init( const int NewSeed )
    {
        seed = NewSeed;
        printf("RndValue1 = %d\n", ( seed ));

        // Skip first values to make PRNG "settle down".

        seed = 500009 * seed + 300119;
        printf("RndValue2 = %d\n", ( seed ));
        seed = 500009 * seed + 300119;
        printf("RndValue3 = %d\n", ( seed ));
    }

    /**
     * @return Random number in the range [0; 1).
     */

    double getRndValue()
    {
        printf("RndValue4 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("RndValue5 = %d\n", seed);

        return((( seed >> 32 ) & 0x3FFFFFFF ) * 9.31322574615478516e-10 );
    }

    /**
     * @return Scale of "raw" random values returned by functions with the
     * "raw" suffix.
     */

    static int32_t getRawScale()
    {
        return( 0x40000000 );
    }

    /**
     * @return Uniformly-distributed random number in the range [0; 1), in the
     * "raw" scale.
     */

    int32_t getUniformRaw()
    {
        printf("UniformRAW1 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("UniformRAW1 = %d\n", seed);

        return( (int32_t) (( seed >> 32 ) & 0x3FFFFFFF ));
    }

    /**
     * @return TPDF random number in the range (-1; 1), in the "raw" scale.
     */

    int32_t getTPDFRaw()
    {
        printf("RndValueRAW1 = %d\n", seed);
        seed = 500009 * seed + 300119;
        printf("RndValueRAW2 = %d\n", seed);
        const int32_t v1 = (int32_t) (( seed >> 32 ) & 0x3FFFFFFF );
        seed = 500009 * seed + 300119;
        printf("RndValueRAW3 = %d\n", seed);
        const int32_t v2 = (int32_t) (( seed >> 32 ) & 0x3FFFFFFF );

        return( v1 - v2 );
    }

private:
    uint64_t seed; ///< The current random seed value.
        ///<
};
Now, by making it print the few iterations on screen, I get the following output:
RndValue1 = 1
?RndValue2 = 800128
?RndValue3 = 639542743
?RndValue4 = 639542743
?RndValue5 = -367371578
?RndValue4 = -367371578
?RndValue5 = -1933728755
?RndValue4 = -1933728755
?RndValue5 = 1256916844
?RndValue4 = 1256916844
?RndValue5 = 55029923
?RndValue4 = 55029923
?RndValue5 = 1896571250
?RndValue4 = 1896571250
?RndValue5 = -314711655
?RndValue4 = -314711655
?RndValue5 = 352186072
?RndValue4 = 352186072
?RndValue5 = -1748128529
?RndValue4 = -1748128529
?RndValue5 = 1681954206
?RndValue4 = 1681954206
?
And there are a couple of things that I do not understand:


seed is defined as uint64_t - how can it possibly become negative (as it does in line 5 on my output RndValue5 = --367371578)??
At least in Python, applying the bitshift operator >> to a negative integer does not give what I can see from C++;

[In211]: s2 = -367371578
?[In211]: s2 >> 32
?Out[211]: -1
?
Maybe you can shed some light and make me understand what I am doing wrong here?
Thank you.
Andrea.

**Comment by avaneev** [comment] 2020-07-21 06:04
Please consider creating a pull request: I can merge your Python version, if possible also add a text file how to use the Python version - it's usually not straight-forward.

**Comment by infinity77** [comment] 2020-07-21 07:00
Hi Alexey,

a few days ago I managed to convert your C++ code to Python, and I am getting exactly the same results as your code - the annoying part was the random number class, but in the end I cracked it.
The Python version works exactly like your C++ one, there is nothing non-straightforward about it - it's actually easier as you don't have to compile anything. It's like this in my code:
```python
   from biteopt import biteopt_minimize
   xf, yf, fun_evals, msg = biteopt_minimize(objective_function, x0, lb, ub, maxfunevals, fglob, M=1, attc=10, args=())
```

I have added a couple of inputs to biteopt_minimize, and in particular:
- `fglob`: if known, the minimum value of the objective function (defaults to -infinity)
- `maxfunevals`: maximum number of functions evaluations allowed

`args` is just additional input arguments to be passed to the objective function (if any).

And a couple of outputs:
- `fun_evals`: number of functions evaluations used (which can be less than the input `maxfunevals` if `fglob` is known and it is attained before reaching the maximum number of functions evaluations provided)
- `msg`: just an integer, with value `0` if `fglob` has been attained before reaching the maximum number of functions evaluations or with value `1` if `maxfunevals` has been exceeded.

One interesting thing I noticed (both with your C++ code and with my Python translation) is that the success rate of the algorithm is dependent on the dimensionality of the problem in a very funny way.

I have done the following:

1. Coded the Rosenbrock function:
    ```python
    def rosen(x):
        # Rosenbrock in Python
        return sum(100.0 * (x[1:] - x[:-1]**2.0)**2.0 + (1 - x[:-1])**2.0)
    ```
    ```cpp
    #include <stdio.h>
    #include "biteopt.h"
    #include <math.h>

    #if !defined( sqr )
         #define sqr( x ) (( x ) * ( x ))
    #endif // !defined( sqr )

    const int N = 12;
    double lb[ N ] = { -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12};
    double ub[ N ] = { 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12};

    double rosen(int ND, const double* x, void* data)
        // Rosenbrock in C++
        {
            double s = 0.0;
            int i;

            for( i = 0; i < N - 1; i++ )
           {
                s += 100.0*sqr(sqr(x[i])-x[i+1])+sqr(x[i]-1.0);
           }
        return( s );
        }
    ```

2. Run the algorithm with dimensions changing from 2 to 20, and for each dimension used 100 random starting points in the domain (-5.12, 5.12) as lower an upper bounds.

3. Measured the success of BiteOpt in terms of how many of the 100 runs have converged to the global optimum (0.0) **before** using all the allowed functions evaluations (2,000) - with a tolerance of 1e-6, exactly as I have done on my webpage for the other optimizers.

This is the table of results:

| Dimension | Success (%) | Evaluations |
|   :---:   |    :---:    |    :---:    |
| 2         | 100         | 405         |
| 3         | 100         | 769         |
| 4         | 100         | 947         |
| 5         | 100         | 1611        |
| 6         | 100         | 1838        |
| 7         | 100         | 1944        |
| 8         | 100         | 1259        |
| 9         | 100         | 496         |
| 10        | 100         | 1547        |
| 11        | 100         | 1980        |
| 12        | **0**       | **N/A**     |
| 13        | 100         | 1804        |
| 14        | 100         | 921         |
| 15        | **0**       | **N/A**     |
| 16        | 100         | 939         |
| 17        | **0**       | **N/A**     |
| 18        | 100         | 653         |
| 19        | **0**       | **N/A**     |
| 20        | **0**       | **N/A**     |

Where `Evaluations` is the average number of function evaluations across all the runs that have attained `fglob` before reaching the maximum number of function evaluations allowed.

What is very curious is, for example, for dimension `N=12`, the algorithm didn't find the global optimum not a single time in the 2,000 functions evaluations allowed, while for `N=11` and `N=13` it found it 100% of the time. 
You can easily replicate this behaviour if you use the code for the Rosenbrock function in your C++ code, an you'll see that it doesn't get below 1e-6 before iteration 4,700. With `N=11` you get it at iteration 1,980, and with `N=13` you get it at iteration 1,804.

Interesting at best :-) .

Andrea.

**Comment by infinity77** [comment] 2020-07-21 07:48
My apologies, please disregard the table... The 100 runs are pointless as BiteOpt does not use the initial point as starting point :-) . I am so used to optimization algorithms taking the initial point into consideration that I completely overlooked that.

That said, it's still interesting that switching from 11 to 12 to 13 dimension you get success/failure/success, not to mention that the number of objective function evaluations varies wildly with the dimensionality:

![figure_1](https://user-images.githubusercontent.com/8988321/88027229-3b7e6380-cb37-11ea-8d05-c9523544f78b.png)

**Comment by avaneev** [comment] 2020-07-21 08:27
Well, this is described at the alogirthm page - the number of function evaluations indeed varies greatly, it's just how it works. As a starting points algorithm generates random values, so I doubt there will be 0 successes if you allow algorithm to self-initialize. In any case, the algorithm is not great for dimensions above 10. You should switch to CMA-ES or my SMA-ES- they are spectacular at higher dimensions.

**Comment by avaneev** [comment] 2020-07-21 08:30
Maybe your results means the algorithm can be improved... But I've used all my powers to try to improve it further, I was not able to improve it further.

**Comment by avaneev** [comment] 2020-07-21 08:54
I, I see you limited to 2000 evaluations, then it's possible it won't converge at higher dimensions. But your observation is indeed interesting - I've never evaluated the algorithm this way.

**Comment by infinity77** [comment] 2020-07-21 09:17
Hi Aleksey,

I haven’t limited the number of function evaluations in the last plot I posted, I simply let the algorithm run until the objective function was less than 1e-6 and recorded how many evaluations were necessary to reach that target.

Now, I don’t know if it’s a peculiarity of the Rosenbrock function or not, but there are unexplained (and very interesting) enormous swings in the number of functions evaluations required to reach the global optimum depending on the dimension. From N=14 onwards it is very pronounced, for example.

I would have expected some sort of linear (or super linear or even exponential) increase in function evaluations but apparently there is something else at play here...

**Comment by avaneev** [comment] 2020-07-21 09:21
Thank you. I will revisit the algorithm and I'll try it on other functions to see if it behaves the same. Maybe algorithm can be revised. Good observation (if I can replicate it).

**Comment by infinity77** [comment] 2020-07-21 09:52
I have replicated my exact Python numbers with your C++ code, by using this Python script to generate a new C++ Rosenbrock function, compile it and run it for all dimensions (your original code is executed untouched):

```python
import os
import numpy

CPP = '''
// Minimization test for the Rosenbrock function

#include <stdio.h>
#include "biteopt.h"
#include <math.h>

#if !defined( sqr )
	#define sqr( x ) (( x ) * ( x ))
#endif // !defined( sqr )

#if !defined( M_PI )
	#define M_PI 3.14159265358979324
#endif // !defined( M_PI )

const int N = %d;
double lb[ N ] = { %s };
double ub[ N ] = { %s };
int iteration = 0;
int printed = 0;

double rosen(int ND, const double* x, void* data)
{
	double s = 0.0;
	int i;

	for( i = 0; i < N - 1; i++ )
	{
		s += 100.0*sqr(sqr(x[i])-x[i+1])+sqr(x[i]-1.0);
	}

    iteration += 1;
    if (s < 1e-6 & printed == 0)
       {
           printf("N = %%-2d Iteration = %%-6d  Fval = %%0.10g\\n", N, iteration, s);
           printed = 1;
       }
	return( s );
}

int main()
{
	double x[ N ];
	double minf;
	biteopt_minimize( N, rosen, NULL, lb, ub, x, &minf, 100000 );
}
'''


def Main():

    cpp_file = 'rosenbrock_test.cpp'
    exe_file = 'test.exe'

    for dimension in range(2, 21):

        lb = -5.12*numpy.ones((dimension, ), dtype=float)
        ub = -lb

        lb = ('%s'%lb.tolist())[1:-1]
        ub = ('%s'%ub.tolist())[1:-1]

        code = CPP%(dimension, lb, ub)
        fid = open(cpp_file, 'wt')
        fid.write(code)
        fid.close()

        os.system('g++ %s -o %s'%(cpp_file, exe_file))
        os.system(exe_file)


if __name__ == '__main__':
    Main()
```

The C++ code spits out the following table:

`N  = 2    Iteration = 405      Fval = 4.461096903e-007`
`N  = 3    Iteration = 769      Fval = 3.193432454e-007`
`N  = 4    Iteration = 947      Fval = 5.415883409e-007`
`N  = 5    Iteration = 1611    Fval = 9.924061126e-007`
`N  = 6    Iteration = 1838    Fval = 3.714127163e-007`
`N  = 7    Iteration = 1944    Fval = 2.560434855e-007`
`N  = 8    Iteration = 1259    Fval = 4.464841693e-007`
`N  = 9    Iteration = 496      Fval = 4.415643832e-007`
`N = 10 Iteration = 1547    Fval = 6.309144892e-007`
`N = 11 Iteration = 1980    Fval = 8.420347825e-008`
`N = 12 Iteration = 4748    Fval = 1.868966861e-007`
`N = 13 Iteration = 1804    Fval = 6.556659926e-007`
`N = 14 Iteration = 921      Fval = 9.279215907e-007`
`N = 15 Iteration = 4392    Fval = 2.612685161e-007`
`N = 16 Iteration = 939      Fval = 7.920773627e-008`
`N = 17 Iteration = 5042    Fval = 2.609617665e-007`
`N = 18 Iteration = 653      Fval = 1.974928135e-007`
`N = 19 Iteration = 6412    Fval = 9.275330039e-007`
`N = 20 Iteration = 2785    Fval = 7.143240522e-008`

**Comment by avaneev** [comment] 2020-07-21 10:10
Interesting... Anyway, needs recheck on a variety of other test functions. Currently I'm busy with other things, I will revisit the algorithm a bit later.

**Comment by avaneev** [comment] 2020-07-21 10:20
Note that algorithm does indeed have a huge dispersion regarding optimization time. Your code catches any first attempt that converges. Maybe the second attempt converged slower. Maybe there's something to it, I'll check it for sure.

**Comment by avaneev** [comment] 2020-07-21 10:24
(when you are calling biteopt_minimize(), it makes up to 10 attempts)

**Comment by infinity77** [comment] 2020-07-21 12:31
Just for fun I have run BiteOpt through 59 benchmarks that support changing the dimensionality of the problem, and to be as general as possible I have shifted symmetric bounds (i.e., if the global minimum is at x = 0 and the bounds are -5.12, +5.12 I have shifted them so that the global minimum is not in the middle of the bounds). Of course this shifting keeps the region where the global minimum is located.

59 pictures attached as a zip file - many of the functions exhibit similar behavior as the Rosenbrock one we discussed above. Food for thought :-) .

[BiteOpt.zip](https://github.com/avaneev/biteopt/files/4953459/BiteOpt.zip)

**Comment by avaneev** [comment] 2020-07-21 19:15
Thank you. I think I've already tried everything to make attempts produce faster results in most cases, for most dimensions, but maybe I'm missing some regularity still... It would be too good for the method to produce best-case results for all dimensionalities, for all attempts. At least I think so.

**Comment by avaneev** [comment] 2020-07-21 19:29
There's one simple fix to reduce swing of solution time is to replace
				const double v = ( j == 0 && InitParams != NULL ?
					wrapParam( rnd, ( InitParams[ i ] - MinValues[ i ]) /
					DiffValues[ i ]) : r );
with simple
const double v =(double)(j)/(PopSize-1);
Meaning that every attempt will be initialized to the same vectors. It's a very "unconventional" approach, but maybe initial solution vectors initialization can be optimized better.

**Comment by avaneev** [comment] 2020-07-21 19:39
or maybe const double v =(double)(j+1)/(PopSize+1);
for method it's just a source of initial information, so there's no "meaning" to that, it can be anything.

**Comment by infinity77** [comment] 2020-07-21 20:42
Doesn't look good... some numbers:

![image](https://user-images.githubusercontent.com/8988321/88104748-28a17880-cba3-11ea-82eb-c3e5ee0d8213.png)
![image](https://user-images.githubusercontent.com/8988321/88104807-44a51a00-cba3-11ea-8d0e-1b152abb4c60.png)

Many more are failing with that change. But thank you for the suggestion :-)

**Comment by avaneev** [comment] 2020-07-22 03:58
A pity. Here's I've come up with a more stable formula:
const double v =(double)j/PopSize+rnd.getRndValue()/PopSize;

And here are reoptimized hyper-parameters for this formula:
// Cost=2.236368
RandProb[ 0 ] = 0.51952897;
RandProb[ 1 ] = 0.94262428;
RandProb2[ 0 ] = 0.26848943;
RandProb2[ 1 ] = 0.06811434;
AllpProb[ 0 ] = 0.31395333;
AllpProb[ 1 ] = 0.99833299;
CentProb[ 0 ] = 0.99751036;
CentProb[ 1 ] = 0.21841604;
CentSpan[ 0 ] = 2.50688178;
CentSpan[ 1 ] = 2.12034783;
ScutProb = 0.06000000;
MantSizeSh = 32.52013407;
MantSizeSh2 = 85.29459692;
PopSizeBase = 11.31421505;
PopSizeMult = 2.63483314;

**Comment by avaneev** [comment] 2020-07-22 04:07
Anyway, for dimensions>10, my SMA-ES is a much better option.

**Comment by infinity77** [comment] 2020-07-22 07:47
Looks kind of OK in general, it still goes ballistic in some objective functions and you can still see wildly swinging evaluations as a function of the dimensionality (see for example the DixonPrice plot, or the Quintic plot), but less than before. I am attaching some pictures with the comparison between the original BiteOpt and your latest suggestions.

For some reason, the modified implementation goes insane for the Plateau function - it can't find any solution for any dimension with up to 200,000 evaluations, while the original implementation solves it easily in 50/60 evaluations irrespective of the dimensionality. The plateau function is an innocent-looking thing like this:

```python
f = 30.0 + sum(floor(abs(x)))
```

But anyway, thank you for all your efforts. One day I\ll find the time to convert your smaesopt to Python too.
[BiteOpt.zip](https://github.com/avaneev/biteopt/files/4958574/BiteOpt.zip)

**Comment by avaneev** [comment] 2020-07-22 09:47
I think I've reached maximum with this algorithm. It requires optimization attempts - if you run only a single attempt, you'll get such "spiky" results. It's just how algorithm works. In practice I run this algorithm with various random seeds in parallel and some instance manages to find a good solution anyway. Some instances are stuck at an unoptimal solution. The algorithm should not be benchmarked with a single optimization attempt.

**Comment by infinity77** [comment] 2020-07-23 05:15
It’s all right Aleksey, I didn’t mean to waste your time, it was just an interesting find, that’s all. I’m very happy with BiteOpt. I’m in the process of adapting a few other global optimization algorithms to Python and at some point I will rerun my benchmarks with BiteOpt and the new algorithms to see what’s the current state of the available optimization algorithms in Python. 

Thank you again for your answers.

**Comment by avaneev** [comment] 2020-07-23 05:46
You are welcome! I'm glad the algorithm works in Python identically.

**Closed** 2021-02-28 18:40 UTC

**Comment by avaneev** [comment] 2021-04-12 06:48
@infinity77 Hello, would you consider updating your 2021 benchmarks to use the latest BiteOpt? You've did a very good job!

It's a lot of work to translate it to Python again, but somebody managed to produce a C++ wrapper for BiteOpt - https://pypi.org/project/biteopt/ - It's not up-to-date, but includes BiteOpt2021.

**Comment by avaneev** [comment] 2021-04-12 06:52
@infinity77 I would also offer you to change your convergence criteria. It should be 1% of the optimal value, not F_min-F_alg_min <1e-6. It's better to use `F_alg_min<=(F_min+abs(F_min)*0.01)`, if F_alg_min==0, the use `F_alg_min<=(F_min+1e-6)`.

**Comment by avaneev** [comment] 2021-04-12 07:01
@infinity77 e.g. if F_min is -4000, using F_min-F_alg_min<1e-6 equates to 1e-10 precision, which for most derivative-free methods requires a lot more iterations. Please see here, it uses 1% optimum tolerance: https://sahinidis.coe.gatech.edu/?q=dfocomp

**Comment by avaneev** [comment] 2021-04-12 07:05
@infinity77 Also, the weighted average in "general results" is not particularly correct way to measure performance, because if e.g. some solver solves a lot of problems in a given small set, it will give better overall results. I think "general results" are better averaged without weighting.

**Comment by infinity77** [comment] 2021-04-12 07:29
Hi @avaneev,

thank you for your suggestions. I understand your comments and you have valid points, but I am unlikely to re-run everything at the moment: first of all, it takes kind of forever to re-run the entire test suite. Second, I had translated your code to Python as I wanted to add some more robust ways to handle objective functions that shoot to infinity or NaN (it happens). 

As for the convergence criteria, there's very few objective functions (and only in SciPy extended/GlobalLib) for which the minimum is that far away. All the other benchmarks have global minima around 0 or less than 10. Of course the benchmarks could be re-run to account for a relative error instead of an absolute one, but I will defer that to some time in the future. I am aware of Sahinidis' study, I have read that paper very many times - you will also notice that pretty much all the global solvers in my test-suite are derivative-free, so what's difficult for one is difficult for all others as well. I am currently writing a paper I hope to submit to the Journal of Global Optimization summarizing all this stuff (solvers and benchmarks): assuming I have the willpower to finish it, I will probably have to adjust/rerun the benchmarks possibly including also commercial solvers.

I am not 100% clear why a weighted average should skew the results as you say: if any algorithm does well in, let's say, the GKLS benchmark (which is the largest), its overall results are going to reflect that - which is exactly the case: MCS, then DualAnnealing, SHGO, Direct and BiteOpt.

**Comment by avaneev** [comment] 2021-04-12 08:12
@infinity77 Well, you can use 0.1% tolerance if that better suits your goals. An absolute value tolerance just isn't practical, I have not seen it used anywhere, even when benchmarking commercial large-scale analytic optimizers. The problem is, even if there are only 10% of functions with F_min like -1000, it makes these 10% of functions unsolvable for most derivative-free methods that aim at a wide range of dimensions. Some optimizers converge very fast on a point after finding a potential optimum region, but this works in low dimensions mainly - I do not see how it's possible to increase precision fast in e.g. 20 dimensions. So, such approach technically favors solvers that converge very fast in low dimensions.

DualAnnealing for example didn't win any single test suite, BiteOpt won 2. Your test suites seem to be diverse, so the weighted calculation does offer benefit to some solvers, if they solve particular suites very well. Alternatively, you could split your suites to e.g. 1-3 dimensions, 4-6, 6+. Then the weighting would be even less needed, and demonstrate solver performance a lot better.

**Comment by avaneev** [comment] 2021-04-12 08:14
@infinity77 As for the BiteOpt2018, it's very outdated. Version 2021 is a lot better, so I just wanted to keep it updated. It's easier to wrap the C++ code than rewrite it now - it become a quite big code.

**Comment by avaneev** [comment] 2021-04-12 08:36
@infinity77 More specifically on weighting. If you do pairwise comparison of BiteOpt and DualAnnealing, BiteOpt wins in 9 suites, DualAnnealing wins in 7 suites. It's counter-intuitive that BiteOpt's final rank is 5 while DualAnnealing's is 2.

**Comment by avaneev** [comment] 2021-04-12 08:43
@infinity77 Well, BiteOpt even wins in pairwise comparison to SHGO. There's just several ways exist to compare performances of solvers. One of which is pairwise comparison of each-solver to each-solver, then summing the number of wins. Averaging, even weighted averaging introduces a lot of extremes. In sports, for example, pairwise comparison is the only feasible way to compare performances due to a lot of implicit variables.

**Comment by infinity77** [comment] 2021-04-12 08:47
No worries @avaneev, I will make sure to include your remarks as soon as feasible for me - I'll find a way to visualize a pairwise comparison and put it nicely on my website/paper.

**Comment by avaneev** [comment] 2021-04-12 09:09
@infinity77 Thanks! If you do the pair-wise comparisons, I do suggest you to split problems in several dimension categories. This way the comparison matrix will be larger and more representative of the performance. For example, if there were only 3 suites, such pair-wise comparison would not be representative. Of course, this does not mean BiteOpt will come out as a winner - I do not know, maybe such comparison will even push BiteOpt lower. However, if you introduce %% tolerance, this will benefit BiteOpt and several other solvers, they won't look so losing compared to MCS.

**Comment by infinity77** [comment] 2021-04-12 09:16
@avaneev  - I am unclear on your proposal of splitting by dimension: do you not have that information in this graph already?

![image](https://user-images.githubusercontent.com/8988321/114371007-5f2f8100-9b80-11eb-90f5-46f1b518c0c3.png)

Of course doing it as a heatmap winner/loser will bring out the comparison better. But being the graphs two-dimensional, it's either a split by benchmark (i.e., 16 pictures) or a split by dimension (5 graphs)

**Comment by avaneev** [comment] 2021-04-12 09:24
@infinity77 I've meant splitting the General Results table by dimension categories. To make problem sets bigger, I think it's useful to combine into 2&3, 4&5, 6+ dimensions. Usually, there's little difference between solving 2 and 3 dimensions, and solving 4 and 5 dimensions, but there is big difference in methodology between solving 2 and 5 dimensions.

**Comment by avaneev** [comment] 2021-04-12 09:26
@infinity77 Then after such splitting, pair-wise comparisons will make more sense: some solvers will win in 2-3 dimensions, some solvers will win in 4-5 dimensions, some solvers will win in 6+ dimensions. This will result in a more balanced score.

**Comment by infinity77** [comment] 2021-04-12 09:32
I believe the GKLS, GlobOpt and RandomFields benchmarks will beg to differ with your assumption that "there's little difference between solving 2 and 3 dimensions". But anyway, I will have to find another way to display that split, the table itself is already bigger than I would like it to be. I'll invent something.

**Comment by avaneev** [comment] 2021-04-12 09:36
If you look at your graphs for dimensions 2&3, I think the correlation is obvious - solvers perform very similar in these dimensions. Then there is a big jump in statistics between dimesions 3 and 4, then 4 and 5 look similar again. There's no discussion about the benchmark problems.

**Comment by infinity77** [comment] 2021-04-12 09:51
![image](https://user-images.githubusercontent.com/8988321/114375694-39f14180-9b85-11eb-9cc3-3128176a151b.png)

As I wrote, I'll have to invent something.

**Comment by avaneev** [comment] 2023-01-07 03:39
@infinity77 Hi! Any chance you can rerun the benchmark using the latest BiteOpt, just for it? It's included in fcmaes for Python: https://github.com/dietmarwo/fast-cma-es

**Comment by avaneev** [comment] 2023-01-17 03:11
@infinity77 Could you please at least update your go_2021 benchmark and include BiteOpt's version you've used there? It's just hugely misleading, and basically puts my work to waste to an outside viewer.
